FROM node:18-alpine

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

EXPOSE 5000

CMD ["npm", "start"]



# FROM node:18 as build-stage

# # RUN npm install -g pnpm

# WORKDIR /app
# COPY package*.json /app/
# RUN npm install --verbose

# COPY ./ /app/
# RUN npm build