FROM node:18-alpine

WORKDIR /src

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]


FROM node:18 as build-stage

RUN npm install -g pnpm

WORKDIR /src
COPY package*.json /src/
RUN pnpm install

COPY ./ /app/
RUN pnpm build