version: "3"

services:
  frontend: 
    build: ./frontend
    ports: 
      - "3000:3000"
    stdin_open: true
    tty: true
  
  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      - "80:80"
    environment:
      - REACT_APP_DOMAIN = "dev-7mpty06oczftshr2.us.auth0.com"
      - REACT_APP_CLIENT_ID = "yAfTGPuAVz3jPLyPislzQJKeSRVwo7hU"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy