version: "3"

services:
  frontend: 
    build: ./frontend
    ports: 
      - "3000:3000"
    stdin_open: true
    tty: true
  
  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      - "80:80"
    environment:
      - REACT_APP_DOMAIN=backend
      - PORT=8080
      - MINIO_HOST=minio
      - MINIO_PORT=9000
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy